# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: bc2f04cbf7b1da1afdd56a98a15f684c2f529a2e0484ff7e1904e9cc84681792d9b7e24578a8b91266d9c34ab05cc0429c00695a0172029495dca33d599f5496

test:
  secret_key_base: 240b86cc9676937f94e5e516568252315b34bb568afc5a6fd47ccc82f5a4b9fdb1a388972168e4ad5de3964fe56797302e1c02e6d4fffe10fa6d381215a6bbb8

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
